# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy necessary files
COPY pyproject.toml ./
COPY README.md ./
COPY LICENSE ./
COPY CHANGELOG.md ./
COPY uv.lock ./
COPY src ./src

# Install dependencies and the package itself
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Expose port if using SSE transport (default is 8000)
EXPOSE 8000

# Set the entrypoint to run the MCP server using the module entry point
ENTRYPOINT ["python", "-m", "f1_mcp_server"]
